Update to AWS SDK for JavaScript (v3)
Innablr/revolver pull request #75
Opened 2024-01-18 00:02 UTC by lyricnz

Very very draft. https://github.com/Innablr/revolver/issues/17

2024-01-18 21:48 UTC, lyricnz commented
Worth reviewing now @abukharov @alutman-innablr .  Only EC2 is properly converted (with the additional arg to the AWS client constructor).  Please let me know how to improve the code, and if I should proceed with the other clients (and/or make a type-specific factory).

2024-01-19 04:10 UTC, alutman-innablr requested changes
Minor note on a `awsConfig` function but otherwise looks good.

Note that this is still using the v2 "style" (e.g. `ec2.startInstances`) just with newer libraries. If/when we implement mocking we might to use v3 style  (e.g `ec2.send(new StartInstancesCommand(...)`). [Full details](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ec2/command/StartInstancesCommand/)

2024-01-19 04:10 UTC, alutman-innablr commented on drivers/ec2.ts
> +    const ec2 = await getAwsClient(EC2, this.accountConfig.assumeRoleArn, this.accountConfig.region);
Might as well replace with `getAwsClientForAccount` for both.

2024-01-19 04:10 UTC, alutman-innablr commented on lib/awsConfig.ts
> +export { getAwsConfig, getAwsClient, getAwsClientForAccount };
`getAwsClient` is only used in one spot in ec2 that could instead use `getAwsClientForAccount`. Might as well remove the export of `getAwsClient`.

2024-01-19 04:18 UTC, alutman-innablr approved these changes

2024-01-19 06:50 UTC, merged

2024-01-21 22:43 UTC, lyricnz commented
> Minor note on a `awsConfig` function but otherwise looks good.
> 
> Note that this is still using the v2 "style" (e.g. `ec2.startInstances`) just with newer libraries. If/when we implement mocking we might to use v3 style (e.g `ec2.send(new StartInstancesCommand(...)`). [Full details](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ec2/command/StartInstancesCommand/)

The new style feels awkward to me